version: '3'

services:
  app-dev:
    container_name: react-app-dev_compose
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8088:8088"
    restart: always


  app-prod:
    container_name: react-app-prod_compose
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8083:8083"
    restart: always
